In [1]:
pip install statsmodels

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import os
# point this at wherever you extracted the archive on your machine
DATA_ROOT = "/home/142401017/Downloads/20news-bydate" 
TRAIN_DIR = os.path.join(DATA_ROOT, "20news-bydate-train")
TEST_DIR = os.path.join(DATA_ROOT, "20news-bydate-test")


In [5]:
class_hireachy = {
    "comp":[
        "comp.graphics",
        "comp.os.ms-windows.misc",
        "comp.sys.ibm.pc.hardware",
        "comp.sys.mac.hardware",
        "comp.windows.x"],
    
    "rec":[
        "rec.autos",
        "rec.motorcycles",
        "rec.sport.baseball",
        "rec.sport.hockey"],

    "sci":[
        "sci.crypt",
        "sci.electronics",
        "sci.med",
        "sci.space"],

    "politics":[
        "talk.politics.misc",
        "talk.politics.guns",
        "talk.politics.mideast"],
    
    "religion":[
        "talk.religion.misc",
        "alt.atheism",
        "soc.religion.christian"]}

In [6]:
DOWNLOADS = "/home/142401017/Downloads/"
stop_words_set = set()
with open(os.path.join(DOWNLOADS,"en.txt"),"r") as f:
    stopwords = f.readlines()
    
    for i in range(len(stopwords)):
        stopwords[i] = stopwords[i][:-1]
        stop_words_set.add(stopwords[i])

In [7]:
def tokenise(text,stop_words_set):
    body = text.lower()      
    lower_case_and_split = body.lower().split()
    
    ans = []
    
    for word in lower_case_and_split:
        word.strip(".,!?()[]:;")
    
        if len(word) > 1 and word.isalpha() and word not in stop_words_set:
            ans.append(word)

    return ans

## Train_data_words has class wise -> terms 
## Trian_data_words will contain all words in that class

In [11]:
import os
import codecs

DATA_ROOT = "/home/142401017/Downloads/20news-bydate" 
TRAIN_DIR = os.path.join(DATA_ROOT, "20news-bydate-train")
TEST_DIR = os.path.join(DATA_ROOT, "20news-bydate-test")


In [12]:
train_corpus = []
for folder in sorted(os.listdir(TRAIN_DIR)):
    FOLDER_PATH = os.path.join(TRAIN_DIR, str(folder))
    if os.path.isdir(FOLDER_PATH):
        for file in sorted(os.listdir(FOLDER_PATH)):
            CURR_FILE_PATH = os.path.join(FOLDER_PATH, file)
            with codecs.open(CURR_FILE_PATH, "r", encoding="utf-8", errors="ignore") as F:
                text = F.read()
                tokens = tokenise(text, stop_words_set) 
                train_corpus.append((tokens, folder))

test_corpus = []
for folder in sorted(os.listdir(TEST_DIR)):
    FOLDER_PATH = os.path.join(TEST_DIR, str(folder))
    if os.path.isdir(FOLDER_PATH):
        for file in sorted(os.listdir(FOLDER_PATH)):
            CURR_FILE_PATH = os.path.join(FOLDER_PATH, file)
            with codecs.open(CURR_FILE_PATH, "r", encoding="utf-8", errors="ignore") as F:
                text = F.read()
                tokens = tokenise(text, stop_words_set)
                test_corpus.append((tokens, folder))

In [67]:
print(train_corpus[0])

(['mathew', 'atheist', 'resources', 'music', 'related', 'atheism', 'contacts', 'apr', 'gmt', 'world', 'mantis', 'resources', 'december', 'atheist', 'resources', 'addresses', 'atheist', 'organizations', 'usa', 'freedom', 'religion', 'foundation', 'darwin', 'fish', 'bumper', 'stickers', 'assorted', 'atheist', 'paraphernalia', 'freedom', 'religion', 'foundation', 'write', 'box', 'wi', 'evolution', 'designs', 'evolution', 'designs', 'sell', 'fish', 'christians', 'stick', 'feet', 'word', 'written', 'deluxe', 'moulded', 'plastic', 'fish', 'postpaid', 'write', 'evolution', 'laurel', 'canyon', 'north', 'ca', 'people', 'san', 'francisco', 'bay', 'area', 'darwin', 'fish', 'lynn', 'gold', 'mailing', 'net', 'people', 'lynn', 'price', 'american', 'atheist', 'press', 'aap', 'publish', 'atheist', 'books', 'critiques', 'lists', 'biblical', 'book', 'bible', 'ball', 'american', 'atheist', 'isbn', 'bible', 'bible', 'contradicts', 'based', 'king', 'james', 'version', 'write', 'american', 'atheist', 'box',

In [65]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

vocabulary = []
word_to_index = {}
doc_frequency = {}

for tokens, label in train_corpus:
    unique_words_in_doc = set(tokens)
    for word in unique_words_in_doc:
        if word not in doc_frequency:
            doc_frequency[word] = 0
        doc_frequency[word] += 1

idx = 0
for word in doc_frequency:
    if doc_frequency[word] > 2: 
        vocabulary.append(word)
        word_to_index[word] = idx
        idx += 1

num_docs_train = len(train_corpus)
idf_dict = {}
for word in vocabulary:
    idf_dict[word] = math.log((num_docs_train) / (doc_frequency[word] + 1)) + 1

print("Vocabulary size :", len(vocabulary))
print(vocabulary)

Vocabulary size : 22460
['twisted', 'conway', 'bizarre', 'atomic', 'study', 'positions', 'accompanied', 'life', 'university', 'grows', 'gmt', 'edition', 'legal', 'back', 'true', 'canyon', 'ball', 'papal', 'isbn', 'wi', 'african', 'western', 'edmund', 'hopkins', 'ranges', 'resources', 'rebut', 'claus', 'assorted', 'quotations', 'woman', 'ironic', 'francisco', 'joe', 'paid', 'uncovering', 'present', 'fax', 'style', 'mantis', 'britain', 'volume', 'small', 'dull', 'gods', 'live', 'gnostic', 'net', 'sell', 'faith', 'people', 'description', 'arguments', 'richard', 'began', 'considers', 'odd', 'pink', 'classical', 'stickers', 'bantam', 'property', 'refuting', 'begins', 'christians', 'young', 'mysteries', 'brain', 'paperback', 'catalog', 'popular', 'laser', 'michael', 'congress', 'charge', 'late', 'beam', 'story', 'archives', 'doctors', 'kingdom', 'worth', 'intellectual', 'fate', 'conduit', 'british', 'laurel', 'post', 'erste', 'world', 'library', 'effect', 'noteworthy', 'events', 'great', 'sh

In [31]:
def trans_tfidf(corpus, vocabulary, word_to_index, idf_dict):
    num_docs = len(corpus)
    vocab_size = len(vocabulary)
    
    X_matrix = np.zeros((num_docs, vocab_size))
    
    for doc_idx in range(num_docs):
        tokens, label = corpus[doc_idx]

        tf_counts = {}
        for word in tokens:
            if word in tf_counts:
                tf_counts[word] = tf_counts[word] + 1
                
            else:
                tf_counts[word] = 1
                
        for word in tf_counts:
            if word in word_to_index:
                col_idx = word_to_index[word]
                raw_tf = tf_counts[word]
                log_tf = 1 + math.log(raw_tf) 
                
                X_matrix[doc_idx][col_idx] = log_tf * idf_dict[word]
                
    return X_matrix


In [44]:
print("Task 1: sci.med vs sci.space")

task1_train = []
y_train1 = []

for tokens, folder in train_corpus:
    if folder == "sci.med" or folder == "sci.space":
        task1_train.append((tokens, folder))
        y_train1.append(folder)


task1_test = []
y_test1 = []
for tokens, folder in test_corpus:
    if folder == "sci.med" or folder == "sci.space":
        task1_test.append((tokens, folder))
        y_test1.append(folder)

X_train1 = trans_tfidf(task1_train, vocabulary, word_to_index, idf_dict)
X_test1 = trans_tfidf(task1_test, vocabulary, word_to_index, idf_dict)

clf1 = LogisticRegression(max_iter=1000)
clf1.fit(X_train1, y_train1)
y_pred1 = clf1.predict(X_test1)

print(f"Precision: {precision_score(y_test1, y_pred1, average='macro')}")
print(f"Recall:    {recall_score(y_test1, y_pred1, average='macro')}")
print(f"F1 Score:  {f1_score(y_test1, y_pred1, average='macro')}")
print()
print(confusion_matrix(y_test1, y_pred1, labels=clf1.classes_))

Task 1: sci.med vs sci.space
Precision: 0.9687485966859335
Recall:    0.9683189765677076
F1 Score:  0.9683458587568177

[[389   7]
 [ 18 376]]


In [45]:
print("Task 2: comp.sys.ibm.pc.hardware vs comp.sys.mac.hardware")

task2_train = []
y_train2 = []
for tokens, folder in train_corpus:
    if folder == "comp.sys.ibm.pc.hardware" or folder == "comp.sys.mac.hardware":
        task2_train.append((tokens, folder))
        y_train2.append(folder)

task2_test = []
y_test2 = []
for tokens, folder in test_corpus:
    if folder == "comp.sys.ibm.pc.hardware" or folder == "comp.sys.mac.hardware":
        task2_test.append((tokens, folder))
        y_test2.append(folder)

X_train2 = trans_tfidf(task2_train, vocabulary, word_to_index, idf_dict)
X_test2 = trans_tfidf(task2_test, vocabulary, word_to_index, idf_dict)

clf2 = LogisticRegression(max_iter=1000)
clf2.fit(X_train2, y_train2)
y_pred2 = clf2.predict(X_test2)

print(f"Precision: {precision_score(y_test2, y_pred2, average='macro')}")
print(f"Recall:    {recall_score(y_test2, y_pred2, average='macro')}")
print(f"F1 Score:  {f1_score(y_test2, y_pred2, average='macro')}")
print()
print(confusion_matrix(y_test2, y_pred2, labels=clf2.classes_))


Task 2: comp.sys.ibm.pc.hardware vs comp.sys.mac.hardware
Precision: 0.8956410426918473
Recall:    0.8942254174397031
F1 Score:  0.8943383084577115

[[361  31]
 [ 51 334]]


In [46]:
print("Task 3: politics vs religion")

task3_train = []
y_train3 = []
for tokens, folder in train_corpus:
    if folder in ["talk.politics.misc", "talk.politics.guns", "talk.politics.mideast"]:
        task3_train.append((tokens, folder))
        y_train3.append("politics")
    elif folder in ["talk.religion.misc", "alt.atheism", "soc.religion.christian"]:
        task3_train.append((tokens, folder))
        y_train3.append("religion")

task3_test = []
y_test3 = []
for tokens, folder in test_corpus:
    if folder in ["talk.politics.misc", "talk.politics.guns", "talk.politics.mideast"]:
        task3_test.append((tokens, folder))
        y_test3.append("politics")
    elif folder in ["talk.religion.misc", "alt.atheism", "soc.religion.christian"]:
        task3_test.append((tokens, folder))
        y_test3.append("religion")

X_train3 = trans_tfidf(task3_train, vocabulary, word_to_index, idf_dict)
X_test3 = trans_tfidf(task3_test, vocabulary, word_to_index, idf_dict)

clf3 = LogisticRegression(max_iter=1000)
clf3.fit(X_train3, y_train3)
y_pred3 = clf3.predict(X_test3)

print(f"Precision: {precision_score(y_test3, y_pred3, average='macro')}")
print(f"Recall:    {recall_score(y_test3, y_pred3, average='macro')}")
print(f"F1 Score:  {f1_score(y_test3, y_pred3, average='macro')}")
print()
print(confusion_matrix(y_test3, y_pred3, labels=clf3.classes_))


Task 3: politics vs religion
Precision: 0.9301708024049262
Recall:    0.9308805588351043
F1 Score:  0.9301027340306077

[[958  92]
 [ 49 919]]


In [49]:
print("Task 4: politics vs sci")

task4_train = []
y_train4 = []
for tokens, folder in train_corpus:
    if folder in ["talk.politics.misc", "talk.politics.guns", "talk.politics.mideast"]:
        task4_train.append((tokens, folder))
        y_train4.append("politics")
        
    elif folder in ["sci.crypt", "sci.electronics", "sci.med", "sci.space"]:
        task4_train.append((tokens, folder))
        y_train4.append("sci")

task4_test = []
y_test4 = []
for tokens, folder in test_corpus:
    if folder in ["talk.politics.misc", "talk.politics.guns", "talk.politics.mideast"]:
        task4_test.append((tokens, folder))
        y_test4.append("politics")
        
    elif folder in ["sci.crypt", "sci.electronics", "sci.med", "sci.space"]:
        task4_test.append((tokens, folder))
        y_test4.append("sci")

X_train4 = trans_tfidf(task4_train, vocabulary, word_to_index, idf_dict)
X_test4 = trans_tfidf(task4_test, vocabulary, word_to_index, idf_dict)

clf4 = LogisticRegression(max_iter=1000)
clf4.fit(X_train4, y_train4)
y_pred4 = clf4.predict(X_test4)

print(f"Precision: {precision_score(y_test4, y_pred4, average='macro')}")
print(f"Recall:    {recall_score(y_test4, y_pred4, average='macro')}")
print(f"F1 Score:  {f1_score(y_test4, y_pred4, average='macro')}")
print()
print(confusion_matrix(y_test4, y_pred4, labels=clf4.classes_))


Task 4: politics vs sci
Precision: 0.9598319877031807
Recall:    0.9514526976084925
F1 Score:  0.9552107671339564

[[ 968   82]
 [  30 1549]]


In [52]:
print("Task 5: politics vs rec vs religion vs sci")

task5_train = []
y_train5 = []
for tokens, folder in train_corpus:
    if folder in ["talk.politics.misc", "talk.politics.guns", "talk.politics.mideast"]:
        task5_train.append((tokens, folder))
        y_train5.append("politics")
        
    elif folder in ["rec.autos", "rec.motorcycles", "rec.sport.baseball", "rec.sport.hockey"]:
        task5_train.append((tokens, folder))
        y_train5.append("rec")
        
    elif folder in ["talk.religion.misc", "alt.atheism", "soc.religion.christian"]:
        task5_train.append((tokens, folder))
        y_train5.append("religion")
        
    elif folder in ["sci.crypt", "sci.electronics", "sci.med", "sci.space"]:
        task5_train.append((tokens, folder))
        y_train5.append("sci")

task5_test = []
y_test5 = []
for tokens, folder in test_corpus:
    if folder in ["talk.politics.misc", "talk.politics.guns", "talk.politics.mideast"]:
        task5_test.append((tokens, folder))
        y_test5.append("politics")
        
    elif folder in ["rec.autos", "rec.motorcycles", "rec.sport.baseball", "rec.sport.hockey"]:
        task5_test.append((tokens, folder))
        y_test5.append("rec")
        
    elif folder in ["talk.religion.misc", "alt.atheism", "soc.religion.christian"]:
        task5_test.append((tokens, folder))
        y_test5.append("religion")
        
    elif folder in ["sci.crypt", "sci.electronics", "sci.med", "sci.space"]:
        task5_test.append((tokens, folder))
        y_test5.append("sci")

X_train5 = trans_tfidf(task5_train, vocabulary, word_to_index, idf_dict)
X_test5 = trans_tfidf(task5_test, vocabulary, word_to_index, idf_dict)

clf5 = LogisticRegression(max_iter=1000)
clf5.fit(X_train5, y_train5)
y_pred5 = clf5.predict(X_test5)

print(f"Precision: {precision_score(y_test5, y_pred5, average='macro')}")
print(f"Recall:    {recall_score(y_test5, y_pred5, average='macro')}")
print(f"F1 Score:  {f1_score(y_test5, y_pred5, average='macro')}")
print()
print(confusion_matrix(y_test5, y_pred5, labels=clf5.classes_))


Task 5: politics vs rec vs religion vs sci
Precision: 0.9109540616512415
Recall:    0.9072572678529888
F1 Score:  0.9088197128081914

[[ 911   24   74   41]
 [  12 1527   10   41]
 [  37   28  860   43]
 [  31   75   32 1441]]


In [56]:
class_word_counts = {}
class_total_words = {}

for tokens, folder in train_corpus:
    if folder not in class_word_counts:
        class_word_counts[folder] = {}
        class_total_words[folder] = 0
        
    for word in tokens:
        if word in word_to_index:
            if word not in class_word_counts[folder]:
                class_word_counts[folder][word] = 0
            class_word_counts[folder][word] += 1
            class_total_words[folder] += 1

In [59]:
def run_naive_bayes(train_data, test_data, target_classes):
    vocab_size = len(vocabulary)
    doc_counts_per_class = {}
    total_docs = len(train_data)
    
    for tokens, actual_class in train_data:
        if actual_class not in doc_counts_per_class:
            doc_counts_per_class[actual_class] = 0
            
        doc_counts_per_class[actual_class] += 1
            
    priors = {}
    for class_name in target_classes:
        class_docs = doc_counts_per_class.get(class_name, 0)
        if class_docs > 0:
            priors[class_name] = class_docs / total_docs
        else:
            priors[class_name] = 0

    nb_class_word_counts = {}
    nb_class_total_words = {}
    for class_name in target_classes:
        nb_class_word_counts[class_name] = {}
        nb_class_total_words[class_name] = 0
    
    for tokens, actual_class in train_data:
        for word in tokens:
            if word in word_to_index:
                if word not in nb_class_word_counts[actual_class]:
                    nb_class_word_counts[actual_class][word] = 0
                nb_class_word_counts[actual_class][word] += 1
                nb_class_total_words[actual_class] += 1

    y_pred = []
    for tokens, folder in test_data:
        best_class = None
        max_log_posterior = -float('inf')
        
        for class_name in target_classes:
            if priors[class_name] > 0:
                log_posterior = math.log(priors[class_name])
                
            else:
                log_posterior = math.log(1e-9)
            
            for word in tokens:
                if word in word_to_index:
                    word_count = nb_class_word_counts[class_name].get(word, 0)
                    word_prob = (word_count + 1) / (nb_class_total_words[class_name] + vocab_size)
                    log_posterior += math.log(word_prob)
                    
            if log_posterior > max_log_posterior:
                max_log_posterior = log_posterior
                best_class = class_name
                
        y_pred.append(best_class)
        
    return y_pred